pipeline {
   agent any
   
   environment {
       DEMO='1.3'
       ENVIRONMENT='Prod'
   }

   stages {
      stage('stage-1') {
         steps {
            echo "This is build number $BUILD_NUMBER of demo $DEMO"
            sh '''
               echo "Using a multi-line shell step"
               ls -l
               pwd
               chmod +x 02/demos/demo1/test.sh
               02/demos/demo1/test.sh
            '''
         }
      }   
      stage('Install-Terraform') {
         steps {
            installTerraform()
         }
        }
      }
}

void installTerraform() {
   sh '''
      su -
      wget https://releases.hashicorp.com/terraform/0.12.21/terraform_0.12.21_linux_amd64.zip
      unzip terraform_0.12.21_linux_amd64.zip && rm terraform_0.12.21_linux_amd64.zip
      mv terraform /usr/bin/terraform
      terraform version
      '''
}
