pipeline {
   agent any
   
   environment {
       DEMO='1.3'
       ENVIRONMENT='Prod'
   }

   stages {
      stage('stage-1') {
         steps {
            echo "This is build number $BUILD_NUMBER of demo $DEMO"
            sh '''
               echo "Using a multi-line shell step"
               ls -l
               pwd
               chmod +x 02/demos/demo1/test.sh
               02/demos/demo1/test.sh
            '''
         }
      }
   }
}
